### PR TITLE
Update version to 1.0.1-SNAPSHOT and fix a MissingPropertyException

### PR DESCRIPTION
**Pull request by sronderos**
Most of the changes are updating the version and ignoring eclipse garbage files.

The bug fix is in the doWithDynamicMethods to ensure that we only look for tenantId on domain objects that are annotated.

This should fix the following JIRA issues: http://jira.codehaus.org/browse/GRAILSPLUGINS-2579, http://jira.codehaus.org/browse/GRAILSPLUGINS-2377

### CODE REVIEW

**Comment by lucastex** [comment]
Hello, I send a pull request with the GRAILSPLUGINS-2579 corrections: https://github.com/multi-tenant/grails-multi-tenant-core/pull/3

**Comment by scryan7371** [comment]
I am getting a merge conflict do to another request that was merged.  Any help in resolving it would be appreciated

**Comment by lucastex** [comment]
This changes corrects (with some other changes) the same problem my pull request does.
Feel free to choose which one should be added to the code repo.

**Comment by sronderos** [comment]
Looks like lucastex's pull request accomplished the same thing.  I've merged in his changes.  It looks like this is now just some ignore files and updating the version to 1.0.1-SNAPSHOT.  I'll close this if you'd rather not bump the version yet.

**Comment by sronderos** [comment]
This is no longer needed

**Pull request closed without merging**
